# Generated by Django 3.1 on 2021-09-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pincode',
        ),
    ]
